name: Generate Snake
permissions:
  contents: write

# Trigger the action on a schedule or manually
on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out the repository
    - uses: actions/checkout@v3  # Use v3 for stability

    # Generates the snake GIF and SVG
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: Theminacious  # Replace with your GitHub username
        gif_out_path: dist/github-contribution-grid-snake.gif  # Path for the GIF
        svg_out_path: dist/github-contribution-grid-snake.svg  # Path for the SVG

    # Show the status of the build (useful for debugging)
    - run: git status

    # Push the generated GIF and SVG files to the repository
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Change to 'main' branch instead of 'master'
        force: true  # Force push to avoid conflicts

    # Deploy the generated files to GitHub Pages (optional)
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # The branch to store the output
        build_dir: dist  # The directory with the generated files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
